### ISSUE TITLE
Error when try to log

### ISSUE THREAD

**Issue by mpanichellaperez** [nicolasdao/aws-cloudwatch-logger#9]
When I try to log different lines into cloud watch  I have this error sporadically, which causes the running process to fail.

![image](https://user-images.githubusercontent.com/91140177/188455260-7adbbd86-950b-49f1-9b50-e0c4e4a28bcb.png)

**Comment by redvivi** [comment]
Same here.

Apparently, this is due to [https://github.com/nicolasdao/aws-cloudwatch-logger/blob/17789e9db27ebb4a6e5677aa7d99e6135dc30267/index.js#L145](url) and fixed in https://github.com/nicolasdao/aws-cloudwatch-logger/pull/7

I suspect that `err.response.data` is undefined.
@nicolasdao , can you please help on this to merge the PR?

**Comment by nicolasdao** [comment]
Hi @redvivi ,

I've just merged your PR. I've bumped the version from 0.1.2 to 0.1.3 and deployed it to NPM.

Thanks a lot for your PR. I truly appreciate this 🙏.

Cheers,

Nic
